### ISSUE TITLE
Document how to export release binaries.

### ISSUE THREAD

**Issue by JonBoyleCoding** [virtual-puppet-project/vpuppr#117]
It's a little unclear in the instructions on the main page - in order to build a release binary, do I need your custom Godot, or just your custom export templates?

**Comment by you-win** [comment]
Just the custom export templates. When hacking on the project, some things might not work without my custom Godot build, but the most important parts should still work (aka loading + tracking a model).

**Comment by you-win** [comment]
Added a while back, the current README contains instructions on exporting now. Closing
