### ISSUE TITLE
Make it easier to differentiate between video devices

### ISSUE THREAD

**Issue by QazCetelic** [virtual-puppet-project/vpuppr#119]
Show a small preview of the selected camera to know which one should be used.
This is useful because it displays 3 possible cameras and I don't know which one I should use.

**Comment by you-win** [comment]
If you are talking about how video devices on Linux are shown as `/dev/video<number>`, that could be [improved](https://superuser.com/questions/1053314/v4l2-identifying-dev-video-via-lsusb).

However, turning on the video device and displaying the preview might require an engine patch. I'll have to think about it some more.

**Comment by QazCetelic** [comment]
My original idea was to display it, but another method that helps to select it would work too.

**Comment by you-win** [comment]
Added (and fixed) in 093bf8d4d14d7801071c11af4dea6bf317f871d3
