### ISSUE TITLE
Feature Request: Perfect Sync models

### ISSUE THREAD

**Issue by korewaChino** [virtual-puppet-project/vpuppr#123]
Add a feature to support Perfect Sync models as an extra module.

Currently this feature is under development at https://github.com/virtual-puppet-project/vp3-ifm, which plans to add both the iFacialMocap protocol and Perfect Sync model support into vpuppr.

## Status

Blocker Issue: godotengine/godot#53244

The following issue causes heavy performance issues when trying to render a Perfect Sync model. This will also need to be addressed upstream.

**Comment by you-win** [comment]
Added in 8b3d947
