### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by Supermagnum** [virtual-puppet-project/vpuppr#125]
Hello, is it possible to move the model to another location?
Is it possible to zoom the model in and out?

**Comment by you-win** [comment]
> is it possible to move the model to another location?

Yes, you would need to change the path the model's config file points to. [File paths for godot apps are described here.](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html) This is not something that will be provided in app.

> Is it possible to zoom the model in and out?

There is a bug in the current release where zoom in/out are mapped to the same action

**Comment by Supermagnum** [comment]
Oh,- I ment on the screen so it doesnt get in the way of things.

**Comment by orowith2os** [comment]
Closing, as I think there's nothing else to be asked. If you have any other questions, feel free to ask on the Discord or this can be reopened.
