### ISSUE TITLE
cool project but is this little bit heavy?

### ISSUE THREAD

**Issue by ArchKubi** [virtual-puppet-project/vpuppr#127]
ı open vpuppr my computer become slower yes my computer not gaming computer
1 - screen problem
2 - my test character is looking in the wrong place. I'm looking up my character is looking down
intel core i3-4150, ram 4GB ddr3 no GPU because too expensive in turkey

https://youtu.be/aVQnFYwLdD8 watch this video

**Comment by you-win** [comment]
> ı open vpuppr my computer become slower yes my computer not gaming computer

Yes the program is heavy and resource intensive. Tracking is CPU-bound whether you have a GPU or not. In comparison with other [similar](https://www.vseeface.icu/) [programs](https://malaybaku.github.io/VMagicMirror/en/), I've observed vpuppr to be slightly _less_ resource intensive.

> 1 - screen problem

This appears to be a problem with transparency. That can be turned off under the "App Settings" menu

> 2 - my test character is looking in the wrong place. I'm looking up my character is looking down

Your model has its head bone oriented upside down. I am working on making this configurable, but for now the only fix is to modify your model.

**Comment by ArchKubi** [comment]
no problem ı love godot and your best keep going bro
