### ISSUE TITLE
Please add support for pipewire 

### ISSUE THREAD

**Issue by Supermagnum** [virtual-puppet-project/vpuppr#130]
PipeWire is a project that aims to greatly improve handling of audio and video under Linux. It provides a low-latency, graph based processing engine on top of audio and video devices that can be used to support the use cases currently handled by both pulseaudio and JACK. PipeWire was designed with a powerful security model that makes interacting with audio and video devices from containerized applications easy, with supporting Flatpak applications being the primary goal. Alongside Wayland and Flatpak we expect PipeWire to provide a core building block for the future of Linux application development.

    Capture and playback of audio and video with minimal latency.
    Real-time Multimedia processing on audio and video.
    Multiprocess architecture to let applications share multimedia content.
    Seamless support for PulseAudio, JACK, ALSA and GStreamer applications.
    Sandboxed applications support.

https://pipewire.org/

**Comment by ItsRogueRen** [comment]
What usecase would pipewire provide? Vpuppr doesn't output any audio, and doesn't record or output any video.

**Comment by orowith2os** [comment]
PipeWire-Pulse is also available, and the pipewire devs stated that they're not trying to pressure anything that doesn't need pipewire to implement it iirc. Also, considering that vpuppr doesn't really have a large use case for audio, it's probably not needed anyways.
