### ISSUE TITLE
Serious model deformation & webcam issue

### ISSUE THREAD

**Issue by EzequielBruni** [virtual-puppet-project/vpuppr#140]
So I just tried the new Linux alpha, and I can honestly say that I love how much work has gone into this. There are a couple of problems, though: Firstly, I can't actually change which camera I want to use. The app always insists on using the same one no matter which is selected in the menu.

Secondly, well... here's the old version:

![Screenshot from 2022-08-05 03-37-22](https://user-images.githubusercontent.com/1215780/183046283-ec469f8d-a8a9-4d73-96d4-8e63187afdb7.png)

Annnnnd here's the new one with the same model:

![Screenshot from 2022-08-05 03-35-40](https://user-images.githubusercontent.com/1215780/183046415-569a03e8-3f96-4ec5-9f79-9e38ad9623d1.png)

I wouldn't even know where to begin troubleshooting this!

**Comment by you-win** [comment]
Regarding the model deformation: press <Spacebar> . This used to be done automatically based on a timer but was/is being reworked. A list of application controls _used_ to be listed in the README, but that's also being rewritten.

I will have to look into the camera selection issue.

**Comment by EzequielBruni** [comment]
Okay! That worked exactly as intended, though it took me a second to realize you meant "space" and not the "period". One of those days I guess. Thank you.

For Alpha level software, this is a fanatastic first release, and I can't wait to see how it grows.
