### ISSUE TITLE
Emulate idle animations

### ISSUE THREAD

**Issue by pasqui23** [virtual-puppet-project/vpuppr#150]
In [AlterEcho](https://www.researchgate.net/publication/354175620_AlterEcho_Loose_Avatar-Streamer_Coupling_for_Expressive_VTubing) ([video presentation](https://youtu.be/ioq4Q-ffNwE?list=PLhPegsM-75z05ZO0u_frike7cy2yZ1GfD&t=3089)) a system to improve vtuber animation is described, including a fairly detailed architectural diagram.

At high level it consist of a set of animations that could get played based on both the streamer's emotion (so an alertness blink would play when surprised for example) and based on several "persona parameters" so that a more energetic persona would fidget more or a more extroverted persona would have a straighter and more confident pose.

It all combines in a system the authors mention has been mistaken for actual full body mocap.

**Comment by you-win** [comment]
Is there text documentation regarding this? It also looks like the paper is locked behind a paywall.

**Comment by pasqui23** [comment]
[Version without paywall](https://github.com/TigerHix/AlterEcho/blob/main/Paper.pdf).
No code that I could find but the high level architecture is described nicely enough in the paper.

**Comment by you-win** [comment]
Okay I think I understand what the paper is talking about.

Basically, it uses facial expression recognition to not only switch the avatar's facial expression but also trigger a pre-baked animation as well.

This could be interesting to implement once I get back around to implementing expression recognition.

**Comment by pasqui23** [comment]
On 27/08/22 20:33, Timothy Yuen ***@***.***> wrote:
> Okay I think I understand what the paper is talking about.
> 
> Basically, it uses facial expression recognition to not only switch the 
> avatar's facial expression but also trigger a pre-baked animation as well.
> 
> This could be interesting to implement once I get back around to 
> implementing expression recognition.

It also include "persona parameters" that plays idle animations and alter the avatar posture depending on their value.

**Comment by you-win** [comment]
Sure, that's a fairly common thing to emulate. I believe VTube Studio does that by default
