### ISSUE TITLE
Droidcam virtual webcam is not recognized in 00d5a8fc3b8d35f60493ba66a048aed43e14a0ac

### ISSUE THREAD

**Issue by pasqui23** [virtual-puppet-project/vpuppr#153]
![immagine](https://user-images.githubusercontent.com/6931743/187075674-db15ca76-3e34-4ead-aaac-8e3213b56075.png)
Note that other programs and even VPuppr from the flatpak is able to use such webcam normally.

**Comment by you-win** [comment]
It seems like you are using Linux. What is the output of `ls /dev/v4l/by-id/` ? This is the command used for OpenSeeFace tracking to find webcams on Linux.

**Comment by pasqui23** [comment]
I doubt that it is the correct command to list webcam as the camera device is reported as /dev/video1

**Comment by you-win** [comment]
Which distribution are you using? I've tested this on debian 10, pop os 22.04, and fedora 34

**Comment by pasqui23** [comment]
NixOS, but consider that another laptop with NixOS too and an included webcam ( this laptop I tested on does not include a webcam) does report devices under /dev/v4l/by-id/ so I think the problem is with DroidCam as I tried a setup where I get my face from my phone via DroidCam and then feed that to vpuppr.

**Comment by pasqui23** [comment]
To clarify: I have 2 laptop with NixOS. The one with a webcam included does report devices under /dev/v4l/by-id/ but the other one does not have any included webcam and so does not have any /dev/v4l directory, even after running DroidCam.

**Comment by you-win** [comment]
Is there a recommended solution for getting camera devices via DroidCam? Otherwise, this issue will be closed
