### ISSUE TITLE
Face traking not working

### ISSUE THREAD

**Issue by pasqui23** [virtual-puppet-project/vpuppr#162]
Despite having connected a USB webcam and starting the tracking via OpenVSeeFace no traking actually get applied to the model.
Looking through the console output nothing seems amiss but while the facke traker with the given PID is running with the given PID, no process seems to be listening on port 11573.

**Comment by pasqui23** [comment]
I get the same problem if I install it via flatpak.

**Comment by ItsRogueRen** [comment]
Don't run OSF separately with the flatpak, and make sure you have the correct camera selected in Vpuppr

**Comment by you-win** [comment]
From [this issue](https://github.com/virtual-puppet-project/vpuppr/issues/153), what is the output of `ls /dev/v4l/by-id/` ? Do any webcams show up in the vpuppr gui?

If you are trying to build from source, the OpenSeeFace binary needs to be included. Follow the [install instructions](https://github.com/virtual-puppet-project/openseeface-tracker) here.

Seeing as you're on Linux, you will need to either:

1. Pack OpenSeeFace into a binary using PyInstaller
2. Use one of the [prepacked binaries from here](https://github.com/you-win/OpenSeeFace/actions/runs/3039823138) (soon to be provided by upstream OpenSeeFace?)

**Comment by pasqui23** [comment]
> From [this issue](https://github.com/virtual-puppet-project/vpuppr/issues/153), what is the output of `ls /dev/v4l/by-id/` ? Do any webcams show up in the vpuppr gui?

I don't think is that bug as I've used an usb cam and it is listed among the webcams to be selected.

> If you are trying to build from source, the OpenSeeFace binary needs to be included. Follow the [install instructions](https://github.com/virtual-puppet-project/openseeface-tracker) here.
> 
> Seeing as you're on Linux, you will need to either:
> 
>     1. Pack OpenSeeFace into a binary using PyInstaller
> 
>     2. Use one of the [prepacked binaries from here](https://github.com/you-win/OpenSeeFace/actions/runs/3039823138) (soon to be provided by upstream OpenSeeFace?)

Those instructions are a bit confusing:
1. The build instruction on openseeface-traker do not mention PyInstaller, only to take the release of OpenSeeFace and copy directories
2. After doing such copy what should I do with the openseeface-tracker directory? How do I tell VPuppr to use this tracker? I tried to copy the directory to `resources/extension/open_see_face`, to no effect.
3.

**Comment by you-win** [comment]
I have updated the README for [openseeface-tracker](https://github.com/virtual-puppet-project/openseeface-tracker) with proper build instructions

**Comment by pasqui23** [comment]
Once I have followed the instructions under ["Generating a PyInstaller binary"](https://github.com/virtual-puppet-project/openseeface-tracker#generating-a-pyinstaller-binary) what should I do with the result ing directory?

**Comment by you-win** [comment]
Place the entire openseeface-tracker repo under vpuppr's `resources/extensions/` directory.

In the future, all vpuppr extensions will be moved to git submodules to reduce repo bloat

**Comment by pasqui23** [comment]
And now I get `Parser Error: The identifier "TrackingBackendInterface" isn't a valid type (not a script or class), or couldn't be found on base "self".` when I click on "Tracking"

**Comment by you-win** [comment]
Please pull the latest changes, I updated the code when updating the readme instructions. As of now, the most up-to-date code will always be in vpuppr (where the folder is called `open_see_face` as opposed to `openseeface-tracker`)

**Comment by you-win** [comment]
The relevant documentation has been updated. Closing
