### ISSUE TITLE
The duck avatar keeps pointing up and the tracking calibration doesn't affect this behaviour 

### ISSUE THREAD

**Issue by Iraito** [virtual-puppet-project/vpuppr#183]
Just like in the title, besides that i also difficulties approaching the rigging for my custom avatar, i'm more than willing to share the avatar itself and get some help directly on how to deal with it.
[Avatar example.zip](https://github.com/virtual-puppet-project/vpuppr/files/9745303/Avatar.example.zip)

**Comment by you-win** [comment]
A few questions:

1. Operating system? (e.g. windows, linux - include distro, mac)
2. Vpuppr release? (e.g. 0.9.0 alpha 2, flatpak, etc)
3. Which tracker is being used? (e.g. OpenSeeFace, iFacialMocap, etc)

**Comment by Iraito** [comment]
Windows11
0.9.0 alpha 2
OpenSeeFace

**Comment by you-win** [comment]
When trying to calibrating the tracker, can you press the <escape> key to hide the UI, then press <spacebar> to calibrate? There's a bug in 0.9.0 alpha 2 where the UI will incorrectly catch keyboard input when visible

**Comment by Iraito** [comment]
I was never able to see an UI specifically for the tracking\calibration but i ended up pressing spacebar and that helped with the calibration, i still don't know how to deal with my 3d model though.

**Comment by you-win** [comment]
There is no UI for calibrating the tracker currently. It's being tracked in #181 .

Regarding your 3d model:

1. Is it a vrm model?
2. What specific issues are you experiencing?

**Comment by Iraito** [comment]
1. No it's not, i can export it in any format if necessary
2:My main issue is that i don't know the workflow, i don't know how i should rig it, for example the eyes should rotate by tracking my eyes, the eyebrows should go up and down (and move diagonally a bit) by tracking my eyebrows, for the mouth i'm still thinking of what method i should use.

**Comment by Iraito** [comment]
![image](https://user-images.githubusercontent.com/3323267/195366967-45cb6b98-e1d3-4b74-96fa-12c4986eec04.png)

I would like to animate the ball like this, i can create shape keys for the brow and add bones to the eyebrows, for the mouth i wouldn't mind using a system similar to the duck's eyes triggered by speech recognition, if you can help me on the basics you can help me bring the blue ball live.

**Comment by you-win** [comment]
> No it's not, i can export it in any format if necessary

Advanced features like mouth tracking can only be automatically mapped onto `vrm` models. Basic `glb` models like the duck must have tracking parameters [manually mapped via code](https://github.com/virtual-puppet-project/vpuppr/blob/master/entities/duck/duck.gd#L47).

> My main issue is that i don't know the workflow

If you are only using blender, you can use [this blender addon] to export a `glb` model as a `vrm` model. If not, code will need to be written in order to move the model's eyes and eyebrows.

**Comment by Iraito** [comment]
> > No it's not, i can export it in any format if necessary
> 
> Advanced features like mouth tracking can only be automatically mapped onto `vrm` models. Basic `glb` models like the duck must have tracking parameters [manually mapped via code](https://github.com/virtual-puppet-project/vpuppr/blob/master/entities/duck/duck.gd#L47).
> 
> > My main issue is that i don't know the workflow
> 
> If you are only using blender, you can use [this blender addon] to export a `glb` model as a `vrm` model. If not, code will need to be written in order to move the model's eyes and eyebrows.

For mouth are we talking voice based recognition? like vowels etc. or webcam tracking? the second one could be easier.
I can't see the link for the addon, is it this one? https://vrm-addon-for-blender.info/en/

**Comment by you-win** [comment]
> For mouth are we talking voice based recognition? like vowels etc. or webcam tracking

Webcam tracking. I need to update the [lip sync](https://github.com/virtual-puppet-project/real-time-lip-sync-gd) library I was using.

> I can't see the link for the addon, is it this one

Sorry I messed up the link. Yes, that is the addon [which is also open source](https://github.com/saturday06/VRM_Addon_for_Blender).

**Comment by Iraito** [comment]
Ok i will try the addon, if i encounter issues i will come back here.

**Comment by you-win** [comment]
There is a [discord server](https://discord.gg/6mcdWWBkrr) listed in the readme for real-time chat. GitHub issues is not a good format for 3d modeling support.
