### ISSUE TITLE
make sure that app-config and other configs are stored in unique locations

### ISSUE THREAD

**Issue by Zutatensuppe** [virtual-puppet-project/vpuppr#67]
> i noticed that theoretically app-config could be overwritten by a normal config, if that config is called app-config
maybe all 'normal' configs should get a prefix attached when saving/loading to prevent this?

That's actually a good point. Maybe appending `model_config_` to the start of all 'normal' configs would make sense.

_Originally posted by @you-win in https://github.com/you-win/openseeface-gd/issues/61#issuecomment-974113503_

**Comment by you-win** [comment]
Solved in the current alpha release
