### ISSUE TITLE
Lip sync support

### ISSUE THREAD

**Issue by you-win** [virtual-puppet-project/vpuppr#83]
Add lip sync support. This will likely need to be done as a GDNative library for performance reasons. Rust will probably be the implementation language.

[uLipSync](https://github.com/hecomi/uLipSync) (MIT) can be used as a reference even though it's a Unity library.

[godot-audio-processing](https://github.com/TokageItLab/godot-audio-processing) Can be used as a reference for feeding data from Godot and maybe interpreting the lip synced data?

NOTE: There's no license for godot-audio-processing, but I did ask on Discord if I could use the repo as a reference 
<img width="775" alt="Capture" src="https://user-images.githubusercontent.com/7788341/144736354-926e76cd-cb5d-4d06-a854-a7fa418253e2.png">

[personal fork of uLipSync](https://github.com/you-win/uLipSync)

[personal fork of godot-audio-processing](https://github.com/you-win/godot-audio-processing)

**Comment by GeorgeS2019** [comment]
@you-win 

Would you be interested [Text to Speech LipSync](https://github.com/kaiidams/voice100/pull/40)?

**Comment by you-win** [comment]
@GeorgeS2019 looks like #90 will be handling your request, as your request is more about TTS than lip syncing. This issue is tracking only lip sync support.

On that note, #88 implements basic lip sync support. I will need to add phoneme (viseme?) detection in a later PR.
